services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local