services:
  servidor:
    container_name: servidor
    image: nginx
    ports:
      - 8000:80
    volumes:
      - paginas:/usr/share/nginx/html
    networks:
      - red

  cliente:
    container_name: cliente
    image: busybox
    command: sleep 1000
    networks:
      - red

volumes:
  paginas:
    name: paginas

networks:
  red:
    name: red